# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
- deployment: VMDeploy
  displayName: DeployOpenEdxTheme
  pool:
    vmImage: 'ubuntu-latest'
  environment:
    name: OpenEdx-Environment
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: | 
            echo updating 5thwork theme
            cd /home/edxbsv/.local/share/tutor/env/build/openedx/themes/edx-theme
            git pull
            tutor local stop
            tutor images build openedx \
              --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/wyworx/edx-platform.git \
              --build-arg EDX_PLATFORM_VERSION=ironwood-custom
            tutor local settheme edx-theme $(tutor config printvalue LMS_HOST) $(tutor config printvalue CMS_HOST)
            tutor local start --detach
