# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
- deployment: VMDeploy
  displayName: DeployOpenEdxTheme
  pool:
    vmImage: 'ubuntu-latest'
  environment:
    name: OpenEdx-Environment
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: | 
            echo my first deployment
            cd /home/edxbsv/.local/share/tutor/env/build/openedx/themes/edx-theme
            pwd
            git pull
            tutor local settheme edx-theme $(tutor config printvalue LMS_HOST) $(tutor config printvalue CMS_HOST)
